# Generated by Django 3.1.3 on 2020-11-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0004_auto_20201110_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
